version: '3'

volumes:
  minioData-nestjsLibsExample: { driver: local }
  keycloakData-nestjsLibsExample: { driver: local }

services:
  minio:
    image: minio/minio
    volumes:
      - minioData-nestjsLibsExample:/data
    ports:
      - $STORAGE_MINIO_PORT:9000
    environment:
      MINIO_ACCESS_KEY: $STORAGE_MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $STORAGE_MINIO_SECRET_KEY
    command: server /data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - $QUEUE_RABBITMQ_PORT:5672
    environment:
      RABBITMQ_USERNAME: $QUEUE_RABBITMQ_USERNAME
      RABBITMQ_PASSWORD: $QUEUE_RABBITMQ_PASSWORD

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    volumes:
      - keycloakData-nestjsLibsExample:/opt/jboss/keycloak/standalone/data/
    ports:
      - 8088:8080
    environment:
      KEYCLOAK_USER: $AUTH_KEYCLOAK_USER
      KEYCLOAK_PASSWORD: $AUTH_KEYCLOAK_PASSWORD
      DB_VENDOR: h2
